[template]
rename = [
  { from="tests/factorial_test.rs", to="tests/factorial_test.rs" },
]

raw = [
  ".github/workflows/build.yml",
  ".github/workflows/release.yml",
]

[[placeholders]]
name = "vendor_name"
type = "string"
prompt = "Vendor name?"
default = "Acme"
